#MinGW Makefile
simplest_ffmpeg_player:
	g++ simplest_ffmpeg_player.cpp -g -o simplest_ffmpeg_player.exe -I /usr/local/include -L /usr/local/lib -lmingw32 -lSDL2main -lSDL2 -lavformat -lavcodec -lavutil -lswscale
clean:
	rm simplest_ffmpeg_player.exe